### ISSUE TITLE
Launch failure with 0.6 (post name change)

### ISSUE THREAD

**Issue by rnkn** [adur1990/Pass-for-macOS#28]
**Describe the bug**

Kudos on a very thorough renaming process. I think most people would have just changed the name of the app but none of the internals.

I think something with this name change has gone awry and is preventing the app from launching for me. After downloading version 0.6, the app doesn’t want to open. Opening will result in the brief opening flash animation, but the menu bar icon will not appear.

Pass for macOS appears in Safari Extensions preferences, but enabling it has no discernible effect.

**To Reproduce**

1. quit Passafari from Activity Monitor
1. drag Passafari.app to Trash
2. download latest release of Pass for macOS
3. unzip and drag to /Applications
4. right-click > open and select open to bypass Apple’s “malicious software" warning
5. launch failure

**Expected behavior**

The app should launch as before and sit in the menu bar. The Safari extension should appear as before.

**Screenshots**

n/a

**Desktop (please complete the following information):**

 - macOS version: 10.15.2
 - Safari version: 13.0.4 (15608.4.9.1.3)
 - Passafari version: 0.6
 - How was Passafari installed (Github release, built self, ...): downloaded from Github releases page

**Additional information**

I put back Passafari 0.5 from the Trash and this works the same as before. (I’m not trying to run them simultaneously though.) I’ve restarted and check System Preferences > Security pane to make sure nothing there preventing launch.

**Comment by adur1990** [comment]
Damnit, I fucked up the signing. I will fix as soon as possible.

**Comment by rnkn** [comment]
No emergency. 0.5 still works just fine.

**Comment by adur1990** [comment]
Fixed in 9dade9f4523e4afe1610c750f5c7ab7e6da8823a
