### ISSUE TITLE
Blue icon text in Safari 14

### ISSUE THREAD

**Issue by rnkn** [adur1990/Pass-for-macOS#36]
## Describe the bug
Hi. I just "upgraded" to Safari 14 and found that the Pass button text is now incongruously blue.

## To Reproduce
1. Begrudgingly upgrade to Safari 14.
2. Open a Safari window with the Pass button in the Toolbar.
3. The Pass button has blue text.

## Expected behavior
I think the Pass button is supposed to have black text.

## Screenshots
<img width="292" alt="Screen Shot 2020-09-17 at 5 47 34 pm" src="https://user-images.githubusercontent.com/1256849/93436262-e4fe8d00-f90d-11ea-9616-e1af7d30906d.png">
<img width="425" alt="Screen Shot 2020-09-17 at 5 49 25 pm" src="https://user-images.githubusercontent.com/1256849/93436439-255e0b00-f90e-11ea-8a7d-bd0a023b9a2e.png">

## Desktop (please complete the following information)
 - macOS version: 10.15.6 (19G2021)
 - Safari version: Version 14.0 (15610.1.28.1.9, 15610)
 - Passafari version: Pass for macOS 0.8.1 
 - How was Passafari installed (Github release, built self, ...): downloaded via GitHub release

## Additional information
Thanks for doing a great job! :)

**Comment by adur1990** [comment]
Hi,

thanks for pointing this out, but unfortunately this is no bug, this is [intended behavior in Safari 14](https://developer.apple.com/forums/thread/651500).

In summary, Apple highlights extensions that currently have access to the page this way.
It's annoying, but this is how it is.
Theoretically I could avoid this by providing an icon for the "active" state, but this would defy the purpose of informing the user which extensions are currently accessing the page.

Interestingly, Apple itself does not comply with this rule, as the privacy report does not turn blue.

**Comment by rnkn** [comment]
I wonder if there is anyone in the world who sees this and thinks "oh thanks Apple, that's certainly 100% clear and not a bug at all."

Thanks for looking into this :)
