### ISSUE TITLE
App apparently requires macOS 10.14 or later?

### ISSUE THREAD

**Issue by rnkn** [adur1990/Pass-for-macOS#37]
## Describe the bug
Hello. In the README requirements section it says macOS Sierra (10.12) or later is required. I have recently downgraded to High Sierra (10.13) and when I launch the app it says macOS 10.14 is required.

## To Reproduce
Launch on macOS High Sierra (10.13).

## Expected behavior
App should launch on High Sierra.

## Screenshots
<img width="532" alt="Screen Shot 2020-12-15 at 12 06 19 am" src="https://user-images.githubusercontent.com/1256849/102090613-657b4e00-3e69-11eb-8f9c-e745b6a7f54b.png">

## Desktop (please complete the following information)
 - macOS version: 10.13.6 (17G14042)
 - Safari version: 13.1.2 (13609.3.5.1.5)
 - Passafari version: 0.8.1
 - How was Passafari installed (Github release, built self, ...): GitHub relase

## Additional information
It seems this is set here:
https://github.com/adur1990/Pass-for-macOS/blob/e91cb9c791ca661aaed84de48ebddfe7d32fb5f2/passformacos.xcodeproj/project.pbxproj#L395
and/or here:
https://github.com/adur1990/Pass-for-macOS/blob/e91cb9c791ca661aaed84de48ebddfe7d32fb5f2/passformacos.xcodeproj/project.pbxproj#L452

**Comment by adur1990** [comment]
Oh dang, thanks for pointing this out. I will inspect this asap.

**Comment by rnkn** [comment]
Thanks!
