### ISSUE TITLE
Customize default keybind shortcuts

### ISSUE THREAD

**Issue by fiskhest** [adur1990/Pass-for-macOS#38]
## Summary
The default shortcut to focus the host app (ctrl+shift+p) might conflict with bindings in other programs or workflows. It would be great if it was possible to customize it according to your own needs by way of a settings dialog window or a configuration file in `~/.config`, 

## Motivation
By allowing the user to customize the default keybind shortcut, we take away frustration caused by conflicting workflows.

## Is your feature request related to a problem? Please describe.
The default binds used might already conflict with other programs or workflows.

**Comment by adur1990** [comment]
Thank you for your suggestion.
I will have a look into this and see what options I have.

**Comment by fiskhest** [comment]
Works perfectly, thank you for the quick turnaround! 💯 🙏 🥇
