### ISSUE TITLE
Unify shortcuts?

### ISSUE THREAD

**Issue by adur1990** [adur1990/Pass-for-macOS#39]
## Summary
Currently, there are two shortcuts, one for the Safari Extension and one for the host app.
This was done because the Safari App Extension API did not allow showing the extension's popover programmatically.
However, macOS 10.14.4 introduced a new API function, `showPopover()`, which does exactly what I need to unify the shortcuts. 

However, now comes the big catch.
I tried to include as many macOS and Safari versions as possible.
The current version of Pass for macOS (0.8.2) is supported beginning from macOS 10.12.
This change would drop all of this "just for convenience".

**Comment by fiskhest** [comment]
These are only my thoughts as an interested fan in the project, of course it's fully up to you based on your own interest and time in supporting more versions, but my $0.02:

Would it be possible to code support for both use cases pending the users running macOS version? Many are stuck with old hardware and it would be sad if they lost the ability to use the program.

**Comment by adur1990** [comment]
II propose to offer two Pass for macOS versions. This repo will remain Pass for macOS and will only support macOS 10.14.4 or newer. The current version (0.9) will be moved to a new repo and called Pass for macOS Legacy and will support macOS 10.12 and newer. Changes to the protocol or other fundamental changes I will try to include in both repos, as far as possible and reasonable. Would this be an acceptable solution?

**Comment by fiskhest** [comment]
From my point of view that is a more than acceptable solution. :100:
