### ISSUE TITLE
update keep failing to update

### ISSUE THREAD

**Issue by phsung** [adur1990/Pass-for-macOS#40]
## Describe the bug
when using the auto update. it downloads, but would report "fail to extract" the update.

## To Reproduce
just update?

## Expected behavior
update to succeed.

## Desktop (please complete the following information)
 - macOS version: big sur 11.1
 - Safari version: 14.02
 - Passafari version: 0.8.2
 - How was Passafari installed (Github release, built self, ...): github zip release

## Additional information
My installation path is in /Users/<username>/Applications  instead of the usual system application path.

**Comment by adur1990** [comment]
Thanks for the note. I use brew to update Pass for macOS, so I never noticed.
