### ISSUE TITLE
[Enhancement] Improve behavior after searching for a password.

### ISSUE THREAD

**Issue by Msouza91** [adur1990/Pass-for-macOS#43]
## Preface
Before getting into the meat I'm sorry for not contributing code, but I don't have a lot of experience or a lot of time to sit with the problem and try to cobble together a half assed fix, but I can take a little time to try and give some minor contribution with a little insight after using your software. Thank you so much for it, it did help me greatly. 

Do you accept donations? I didn't see it on the README. On to the order of business...

## Summary
Clear the search box and reset the state after copying the selected password for clipboard

## Motivation
After selecting a password one has to get the mouse to the x on the search box to be able to search for another password, even after a long time, it breaks the flow and makes using the tool just a tiny bit fussy.

## Is your feature request related to a problem? Please describe.
It is quite frustrating to use the keyboard shortcut on the intention of avoiding to grab the mouse for a pass and end up having to grab the mouse anyway.

## Describe alternatives you've considered
Clearing up the search box and grabbing the cursor after pass selection is IMO the best scenario, but you could consider checking for a press on the Esc key or with the cleanup timeout.

## Additional context
By extension this is the same issue if you tab down to some option by mistake and instinctively pressing Esc and trying again, but the you are zucked cause the search is stuck.

The solution proposed shouldn't impact development of other features significantly and is a major quality of life improvement since people using pass are users with a probably more keyboard driven workflow.

**Comment by adur1990** [comment]
Thank you for your suggestion.
In fact, the current behavior has also bothered me and I am currently evaluating alternatives.
The first option I'm currently testing is that you can switch between the search results and the search box with `tab` and `shift-tab`.
The second alternative is the one you suggested.
As soon as you select a password, the status of the popover is reset.

According to my findings I will probably implement both.
As soon as you choose a password the state will be reset, i.e., clearing the search box and empty the search results.
But if you `tab` from the search field to the search results during the search, you will be able to `tab` or `shift-tab` back to the search field.

**Comment by adur1990** [comment]
Maybe a short note on donations.
At the moment there is no way to donate anything to me.
This is mainly because I would otherwise feel so under pressure.
Currently all my projects are pretty small and pure hobbies that I actually implement for my own workflows.
If I would accept donations now, I would feel too obligated.
Then my hobbies would suddenly become work with obligations.
I want to avoid that.
I am absolutely clear that it doesn't have to be that way and that donations are small attentions that are not actually accompanied by obligations.
But I think I would put too much pressure on myself, so I would rather not accept donations.
I'm just happy that there are a lot more people than I thought who find this little tool useful, use it and make constructive suggestions to push this project forward and make it better.

**Comment by Msouza91** [comment]
> Thank you for your suggestion.
> In fact, the current behavior has also bothered me and I am currently evaluating alternatives.
> The first option I'm currently testing is that you can switch between the search results and the search box with `tab` and `shift-tab`.
> The second alternative is the one you suggested.
> As soon as you select a password, the status of the popover is reset.
> 
> According to my findings I will probably implement both.
> As soon as you choose a password the state will be reset, i.e., clearing the search box and empty the search results.
> But if you `tab` from the search field to the search results during the search, you will be able to `tab` or `shift-tab` back to the search field.

Implementing both would be absolutely dreamy! I hope you manage some time to make it happen. Awesome project man.

**Comment by adur1990** [comment]
Implemented in commit 421236c1a6e3585859bf999a49fcd2b8012a053d. Will be included in the next release.
