### ISSUE TITLE
Can't assign any shortcuts in preference menu v0.11.1

### ISSUE THREAD

**Issue by AnotherProksY** [adur1990/Pass-for-macOS#45]
## Describe the bug
Can't assign any shortcuts in preference menu.

## To Reproduce
1. Delete existing shortcut
2. Click out to deselect `Shortcut` field
3. Try to click `Shortcut` field again

## Expected behavior
It will select `Record Shortcut` field to input new shortcut.

## Screenshots
![Imgur](https://media.giphy.com/media/EtGwBGHlJT05ZSUyvd/giphy.gif)

## Desktop (please complete the following information)
 - macOS version: Big Sur 11.1
 - Safari version: 14.0.2
 - Pass for macOS version: 0.11.1
 - How was Pass for macOS installed (Github release, built self, ...): homebrew

## Additional information
1. Clicking `Record Shortcut` field changes to `Press shortcut` for one sec and then goes back to previous state.
2. After double clicking `Record Shortcut` field it changes to `Press shortcut`, but then you can't type any combinations, only plain text value.
3. If you write in plain text, deselect field, click on delete `x` button, then you can write in new shortcut.

**Comment by adur1990** [comment]
Thank you for pointing out this issue. I can reproduce this and have a look into this asap.

**Comment by adur1990** [comment]
This is now fixed in v0.11.2.
