### ISSUE TITLE
Incompatible with non-default `PASSWORD_STORE_DIR`

### ISSUE THREAD

**Issue by indiv0** [adur1990/Pass-for-macOS#48]
## Describe the bug
Searching for any password results in "No password found".

## To Reproduce
Move your `~/.password-store` directory to any other location (like `/Users/indiv0/src/pass`) and set the `$PASSWORD_STORE_DIR` to the path of the new directory. Attempt to use Pass-for-macOS to find a password.

## Expected behavior
Pass-for-macOS should read the `$PASSWORD_STORE_DIR` environment if available (from `.profile` maybe?), or it should be configurable.

## Desktop (please complete the following information)
 - macOS version: 11.2.3
 - Safari version: 14.0.3 (16610.4.3.1.7)
 - Pass for macOS version: 0.11.2-beta
 - How was Pass for macOS installed (Github release, built self, ...): Github release

**Comment by adur1990** [comment]
Thank you for pointing out this issue. I will investigate asap.

**Comment by adur1990** [comment]
Hi, I think I resolved the issue. Please update to the recent version 0.11.3 and give it a try.
Please feel free to reopen this issue or to create a new one if it does not work.

**Comment by indiv0** [comment]
Excellent thanks! I'll give it a try.

**Comment by SeniorMars** [comment]
I think I have the same issue? I transfered over all my passwords, but it is not recognzing anyo of them. I have 11.4 and on a m1 pro
