### ISSUE TITLE
unable to open .gpg file with '(' character

### ISSUE THREAD

**Issue by phsung** [adur1990/Pass-for-macOS#51]
for example I have a password store file named in:

 .password-store/foo_dir/bar_(with_bracket).gpg

when trying to open it (the search list drop down did able to show the entry, with the bracket), it just do nothing. I am suspecting that has to do with '(' or ')' character in the entry.

**Comment by adur1990** [comment]
Thank you for opening this issue. I will have a look in to this ASAP.
Just for good measure: all other cases work?
So you can use Pass for macOS except for the cases with brackets?

**Comment by phsung** [comment]
(  and '  doesn't work.
@ and - works
I haven't try any other symbolic chars.
