### ISSUE TITLE
Pass for macos is not running

### ISSUE THREAD

**Issue by ErnestDong** [adur1990/Pass-for-macOS#52]
## Describe the bug
Here it shows
![image](https://user-images.githubusercontent.com/45593614/132228473-352bc3bb-4fee-4755-9b57-2974e53f9739.png)

## To Reproduce
```sh
brew install passformacos # with pass and pinentry-mac
```
just right click open but failed to launch

## Expected behavior
pass for macos running with only browser extension

<img width="1072" alt="截屏2021-09-06 下午10 01 20" src="https://user-images.githubusercontent.com/45593614/132228774-aedcc7fa-ea4a-4fd4-8c15-55ebe4c06586.png">

## Desktop (please complete the following information)
 - macOS version: 11.5.2
 - Safari version: 14.1.2
 - Pass for macOS version: 0.11.3
 - How was Pass for macOS installed (Github release, built self, ...): `brew install pass`

## Additional information
Add any other information about the problem here.

**Comment by ErnestDong** [comment]
Thank you for your awesome package

**Comment by adur1990** [comment]
Hi,

thank you for using Pass for macOS.
Pass for macOS needs the host application running.
So, please follow the [README](https://github.com/adur1990/Pass-for-macOS#usage) instructions to start Pass for macOS.

**Comment by ErnestDong** [comment]
but I just failed to open the host app 😢

**Comment by adur1990** [comment]
Okay, sorry to hear that. Can you explain what the problem is? Do you see any error message?

**Comment by ErnestDong** [comment]
No. As I ctrl click and ask for open, nothing happens. Though I can see the safari extension running, I can't see the host program

**Comment by ErnestDong** [comment]
fixed with accidentally reinstall macOS

**Comment by SeniorMars** [comment]
It still doesn't work for me.

**Comment by nielsk** [comment]
I can't get it to work either
