### ISSUE TITLE
Request: Add to raycast

### ISSUE THREAD

**Issue by SeniorMars** [adur1990/Pass-for-macOS#54]
## Summary
[Raycast](https://www.raycast.com/) is a popular MacOS app that allows a user to basically launch and use scripts in one place. I would like to possibly integrate pass with raycast.

## Motivation
Imagine one place, where you can control everything.

## Is your feature request related to a problem? Please describe.
No problem, but a request.

## Describe alternatives you've considered
I've considered using just pass for macos, but I feel like it takes too much space in my menu bar.

**Comment by adur1990** [comment]
Thank you for the suggestion.
However, there are no plans from my side.
To be honest, I never heard of raycast before I don't get the concept.

Further, I'm not sure how this would work.
One would probably also need to integrate pass and its dependencies into raycast before adding Pass for macOS.

However, I'm happy to receive pull requests.
If you are interested in integrating Pass for macOS into raycast and create a pull request, I would really consider integrating it.

So, as there are no plans from my side, I close this issue for now.
