### ISSUE TITLE
The app doesn't get focus unless clicked

### ISSUE THREAD

**Issue by sahinakkaya** [adur1990/Pass-for-macOS#61]
## Describe the bug
I don't know if it is only me or this is expected behaviour but the app doesn't get focus unless clicked.

## To Reproduce
Activate the app via keybinding or by clicking its icon in the menu bar and search for some password. The password list cannot be navigated with arrow keys unless you click to the list.

## Expected behavior
I expect the app to get focus when it is activated.

## Desktop Environment
 - macOS version: 13.2.1
 - Safari version: irrelevant
 - Pass for macOS version: v0.11.4
 - Install method: `brew install --cask adur1990/tap/passformacos`

**Comment by sahinakkaya** [comment]
Since no one cared, I decided to implement this by myself and guess what I found: you can navigate the list with Tab/Shift+Tab [*](https://github.com/adur1990/Pass-for-macOS/blob/56a826a43514ed36641f9eb135cb0ca4415bd7d6/passformacos/ViewController.swift#L92)

I might still implement the same functionality for arrow keys but currently this looks OK to me.

**Comment by adur1990** [comment]
Hi,

this is intended behaviour.
When you search for a password, your focus is on the search field, so the arrow keys do what arrow keys do in a text field: move the cursor.
You have to change the focus to the list by pressing tab or click, then you can use the arrow keys.
